name: Deploy-3

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' # every day at 6:00 am UTC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.x'
      - name: Wait for Test
        uses: fountainhead/action-wait-for-check@v1.1.0
        with:
          checkName: test
          token: ${{ github.token }}
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          pip install -r requirements.txt
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: Canada-udp.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
      - name: Run Script
        run: timeout 5400 python Bot.py --accounts ${{ secrets.KEYS3 }} --headless --fast --discord ${{ secrets.webhook }} --privacy --wfd ${{ github.workflow }}
      - name: Retry
        if: ${{ failure() }}
        run: timeout 1800 python Bot.py --accounts ${{ secrets.KEYS3 }} --headless --fast --privacy --wfd ${{ github.workflow }}
